import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <div
        className={`w-full min-h-screen flex flex-col justify-center items-center bg-gray-100`}
      >
        <Head>
          <title>Image Uploader</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="w-full h-full flex flex-grow flex-col justify-center items-center flex-wrap">
          <Component {...pageProps} />
        </main>
        <footer className="w-full py-4 flex flex-col justify-center items-center">
          <p className="text-gray-400 font-bold">
            created by{" "}
            <a
              href="https://github.com/CesarAOrtiz"
              className="text-gray-500 underline"
            >
              César Ortiz
            </a>{" "}
            - <a href="https://devchallenges.io/">devChallenges.io</a>
          </p>
        </footer>
      </div>
    </>
  );
}

export default MyApp;
