import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <div
        className={`w-full min-h-screen flex flex-col justify-center items-center bg-gray-100`}
      >
        <Head>
          <title>Image Uploader</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main
          className="w-full h-full flex justify-center items-center flex-wrap"
          style={{ justifyContent: "space-around" }}
        >
          <Component {...pageProps} />{" "}
        </main>
      </div>
    </>
  );
}

export default MyApp;
