import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import style from "../styles/Home.module.css";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <div className={style.container}>
        <Head>
          <title>Image Uploader</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main
          className={style.content}
          style={{ justifyContent: "space-around" }}
        >
          <Component {...pageProps} />{" "}
        </main>
      </div>
    </>
  );
}

export default MyApp;
